foreground            #E1DFED
background            #1A0F12
selection_foreground  #E1DFED
selection_background  #682537

active_tab_foreground     #E1DFED
active_tab_background     #35252a
inactive_tab_foreground   #5E5659
inactive_tab_background   #1A0F12

active_border_color   #5083C7
inactive_border_color #35252a
url_color             #81A1C1

# Standard ANSI
color0       #30292C
color8       #5E5659
color1       #BF616A
color9       #e06c75
color2       #A3BE8C
color10      #B5C985
color3       #EBCB8B
color11      #D08770
color4       #81A1C1
color12      #83A4A6
color5       #B48EAD
color13      #D18498
color6       #88C0D0
color14      #B9C0E5
color7       #E1DFED
color15      #D7D3EB
