foreground            #CED4D4
background            #222526
selection_foreground  #CED4D4
selection_background  #3f5055

active_tab_foreground     #CED4D4
active_tab_background     #383D3F
inactive_tab_foreground   #5A6163
inactive_tab_background   #222526

active_border_color   #8DA3A3
inactive_border_color #383D3F
url_color             #8A94A8

# Standard ANSI
color0       #2B2E2F
color8       #5A6163
color1       #A88A8A
color9       #B89C9C
color2       #8AA894
color10      #9CB8A6
color3       #A8A88A
color11      #B8B89C
color4       #8A94A8
color12      #9CA6B8
color5       #9B8AA8
color13      #AB9CB8
color6       #8AA8A8
color14      #9CB8B8
color7       #CED4D4
color15      #E2E8E8
