#!/bin/sh

_ps="dwlb swww-daemon hypridle aslstatus dunst mako kitty"
for _prs in $_ps; do
    if [ "$(pidof "${_prs}")" ]; then
         killall -9 "${_prs}"
    fi
 done

systemctl --user stop move-pdf.path &

TMUXNEW=("tmux" "new" "-s" "_home" "-c" "~")
TMUXARGS=("tmux" "a")
if   pidof -x tmux 2> /dev/null;  then
    tmcmd="${TMUXARGS[@]:0:2}"
else
    tmcmd="${TMUXNEW[@]:0:6}"
fi

mako &

systemd-inhibit --what=handle-lid-switch sleep infinity &

systemctl --user start move-pdf.path &

swww-daemon &

wl-paste --type image --watch cliphist store &
wl-paste --type text --watch cliphist store &

(sleep 0.2; easyeffects --gapplication-service) &

hypridle &

(dwlb -ipc -scale 2; sleep 0.2) &

aslstatus -s | dwlb -status-stdin all  &

kitty -e $tmcmd

exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots
