#!/usr/bin/env bash

THEME_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/shell-theme.sh"
if [ -f "$THEME_FILE" ]; then
    source "$THEME_FILE"
else
    echo "Error: Theme file not found at $THEME_FILE"
    exit 1
fi

_ps="swww-daemon swayidle mako foot somebar someblocks"
for _prs in $_ps; do
    if pidof "${_prs}" > /dev/null 2>&1; then
         killall -9 "${_prs}"
    fi
done


_WAYLAND_VARS=(
    WAYLAND_DISPLAY XDG_RUNTIME_DIR DISPLAY XDG_CURRENT_DESKTOP
    XDG_SESSION_TYPE XDG_SESSION_DESKTOP GDK_SCALE QT_QPA_PLATFORM
    QT_STYLE_OVERRIDE SDL_VIDEODRIVER MOZ_ENABLE_WAYLAND
    ELECTRON_OZONE_PLATFORM_HINT OZONE_PLATFORM BEMENU_OPTS WALLPAPER
)

systemctl --user import-environment "${_WAYLAND_VARS[@]}"
dbus-update-activation-environment --systemd "${_WAYLAND_VARS[@]}"

# Silence background services to prevent FD pollution
mako >/dev/null 2>&1 &
systemd-inhibit --what=handle-lid-switch sleep infinity >/dev/null 2>&1 &
swaybg -i "$WALLPAPER" -m fill >/dev/null 2>&1 &
wl-paste --type image --watch cliphist store >/dev/null 2>&1 &
wl-paste --type text --watch cliphist store >/dev/null 2>&1 &
easyeffects --gapplication-service >/dev/null 2>&1 &
swayidle >/dev/null 2>&1 &
someblocks -s /tmp/mybar &

# Services & Daemons
systemctl --user restart kanata
foot --server --config="${XDG_CONFIG_HOME:-$HOME/.config}/foot/foot-launcher.ini" >/dev/null 2>&1 &
dwlctl reload-colors

# tmux variables
TMUXNEW=("tmux" "new" "-s" "home" "-c" "~")
TMUXARGS=("tmux" "a")

if pidof -x tmux > /dev/null 2>&1; then
    tmcmd="${TMUXARGS[@]}"
else
    tmcmd="${TMUXNEW[@]}"
fi

sleep 0.2

# use separate foot process/ footclient only for launchers/menus
setsid foot ${tmcmd} >/dev/null 2>&1 &

exec somebar -s /tmp/mybar
