foreground            #2c3328
background            #f4f6f0
selection_foreground  #2c3328
selection_background  #d3debb

active_tab_foreground     #2c3328
active_tab_background     #b3bba9
inactive_tab_foreground   #77856b
inactive_tab_background   #f4f6f0

active_border_color   #5e8b54
inactive_border_color #b3bba9
url_color             #427b9c

# Standard ANSI
color0       #f4f6f0
color8       #77856b
color1       #ab4a4a
color9       #c25e5e
color2       #5e8b54
color10      #72a167
color3       #a07b32
color11      #b88d3d
color4       #427b9c
color12      #5391b5
color5       #8a5a8a
color13      #a16ba1
color6       #3c8b8b
color14      #4ba3a3
color7       #2c3328
color15      #1a1e17
