foreground            #D1DDE3
background            #261A1D
selection_foreground  #D1DDE3
selection_background  #743243

active_tab_foreground     #D1DDE3
active_tab_background     #3e3537
inactive_tab_foreground   #7D7276
inactive_tab_background   #261A1D

active_border_color   #5083C7
inactive_border_color #3e3537
url_color             #81A1C1

# Standard ANSI
color0       #302528
color8       #7D7276
color1       #BF616A
color9       #e06c75
color2       #A3BE8C
color10      #A8C2A7
color3       #EBCB8B
color11      #D9A286
color4       #81A1C1
color12      #83A4A6
color5       #B48EAD
color13      #D18498
color6       #88C0D0
color14      #B9C0E5
color7       #D1DDE3
color15      #D7D3EB
