foreground            #D7D7C8
background            #16181D
selection_foreground  #D7D7C8
selection_background  #31394e

active_tab_foreground     #D7D7C8
active_tab_background     #2A2F38
inactive_tab_foreground   #525866
inactive_tab_background   #16181D

active_border_color   #8999A8
inactive_border_color #2A2F38
url_color             #7591C4

# Standard ANSI
color0       #1F2229
color8       #525866
color1       #C47575
color9       #D98C8C
color2       #87A677
color10      #9EBF8C
color3       #C4A375
color11      #D9B88C
color4       #7591C4
color12      #8CA6D9
color5       #A375C4
color13      #B88CD9
color6       #75C4B9
color14      #8CD9CD
color7       #D7D7C8
color15      #E8E8DF
