foreground            #1A1A1A
background            #F2F0E5
selection_foreground  #1A1A1A
selection_background  #f6f3e7

active_tab_foreground     #1A1A1A
active_tab_background     #DFDBC3
inactive_tab_foreground   #666359
inactive_tab_background   #F2F0E5

active_border_color   #2D4F67
inactive_border_color #DFDBC3
url_color             #2D4F67

# Standard ANSI
color0       #242424
color8       #666359
color1       #8C2F32
color9       #B33D41
color2       #3E613E
color10      #4D7A4D
color3       #94631A
color11      #B37720
color4       #2D4F67
color12      #3B6685
color5       #6B4A6B
color13      #8C618C
color6       #2A6B62
color14      #368C80
color7       #1A1A1A
color15      #000000
