foreground            #1A1A1A
background            #F2EFE2
selection_foreground  #1A1A1A
selection_background  #f8f4e5

active_tab_foreground     #1A1A1A
active_tab_background     #DBD6BD
inactive_tab_foreground   #6B685E
inactive_tab_background   #F2EFE2

active_border_color   #3E5C5C
inactive_border_color #DBD6BD
url_color             #2D5A82

# Standard ANSI
color0       #242424
color8       #6B685E
color1       #942D2D
color9       #B83B3B
color2       #3D6B3D
color10      #4A824A
color3       #8F661B
color11      #A87921
color4       #2D5A82
color12      #3B73A1
color5       #7A3D7A
color13      #944D94
color6       #1B7A72
color14      #219489
color7       #1A1A1A
color15      #000000
