foreground            #D1CED4
background            #232126
selection_foreground  #D1CED4
selection_background  #483e56

active_tab_foreground     #D1CED4
active_tab_background     #38353D
inactive_tab_foreground   #5C5861
inactive_tab_background   #232126

active_border_color   #9BA8C8
inactive_border_color #38353D
url_color             #94A9C7

# Standard ANSI
color0       #2B292E
color8       #5C5861
color1       #C79393
color9       #D9A9A9
color2       #94B394
color10      #A9C9A9
color3       #D1B894
color11      #E6CCAA
color4       #94A9C7
color12      #A9BDE0
color5       #B394B3
color13      #C9A9C9
color6       #94B3B3
color14      #A9C9C9
color7       #D1CED4
color15      #E2DFE6
