set -g @ACCENTCL "#9BA8C8"
set -g @BGDIM "#1A181C"
set -g status-style 'fg=color15 bg=color0'
# setw -g window-status-style 'fg=color7'
# setw -g window-status-current-style 'bg=#232126 fg=color15 bold'
set -g window-status-bell-style 'bg=red,nobold'
# set -g popup-border-style "fg=color7 bg=default"
set -wg mode-style 'bg=#9BA8C8'
