foreground            #3d353b
background            #e9daca
selection_foreground  #3d353b
selection_background  #dbb48c

active_tab_foreground     #3d353b
active_tab_background     #b4a395
inactive_tab_foreground   #cfb7a4
inactive_tab_background   #e9daca

active_border_color   #A3839E
inactive_border_color #b4a395
url_color             #527E93

# Standard ANSI
color0       #e9daca
color8       #cfb7a4
color1       #C47379
color9       #DD8B74
color2       #7DA291
color10      #94B5A5
color3       #D8A05C
color11      #E5AC60
color4       #527E93
color12      #6D97AC
color5       #A3839E
color13      #B599B1
color6       #6B9E9E
color14      #85B5B5
color7       #6e5d6b
color15      #3d353b
