foreground            #EDEDDA
background            #12080B
selection_foreground  #EDEDDA
selection_background  #446063

active_tab_foreground     #EDEDDA
active_tab_background     #383836
inactive_tab_foreground   #5E5E5A
inactive_tab_background   #12080B

active_border_color   #98c379
inactive_border_color #383836
url_color             #81A1C1

# Standard ANSI
color0       #302e2c
color8       #5E5E5A
color1       #BF616A
color9       #e06c75
color2       #A3BE8C
color10      #B5C985
color3       #EBCB8B
color11      #d19a66
color4       #81A1C1
color12      #83A4A6
color5       #B48EAD
color13      #D18498
color6       #88C0D0
color14      #B9C0E5
color7       #CCCCC0
color15      #EDEDDA
