set -g @ACCENTCL "#9a7895"
set -g @BGDIM "#f2f0f1"
set -g status-style 'fg=color15 bg=color0'
# setw -g window-status-style 'fg=color7'
# setw -g window-status-current-style 'bg=#f2f0f1 fg=color15 bold'
set -g window-status-bell-style 'bg=red,nobold'
# set -g popup-border-style "fg=color7 bg=default"
set -wg mode-style 'bg=#9a7895'
