foreground            {{{{custom.myfront}}}}
background            {{{{custom.mysurface}}}}
selection_foreground  {{{{custom.myvisual}}}}
selection_background  {{{{custom.myfront}}}}

active_tab_foreground     {{{{custom.mysurfacedim}}}}
active_tab_background     {{{{custom.myfront}}}}
inactive_tab_foreground   {{{{custom.mytext}}}}
inactive_tab_background   {{{{custom.mysurface}}}}

active_border_color   {{{{custom.mysurfaceacc}}}}
inactive_border_color {{{{custom.mysurfacedim}}}}
url_color             {{{{custom.myaccent}}}}

color0       {{{{custom.mysurfacedim}}}}
color8       {{{{custom.mysurfaceacc}}}}
color1       {color1}
color9       {color9}
color2       {color2}
color10      {color10}
color3       {color3}
color11      {color11}
color4       {color4}
color12      {color12}
color5       {color5}
color13      {color13}
color6       {color6}
color14      {color14}
color7       {{{{custom.mytextmid}}}}
color15      {{{{custom.mytext}}}}
