* {{
  bga: {{{{custom.myblack}}}}CC;     
  bg0: {{{{custom.myblack}}}};     
  bg1: {{{{custom.mysurface}}}};
  bg2: {{{{custom.mysurfacedim}}}}; 
  bg3: {{{{custom.mysurfaceacc}}}};

  fg1: {{{{custom.mytext}}}};     
  fg2: {{{{custom.myfront}}}}; 

  clr1: {color1};
  clr2: {color2};
  clr3: {color3};
  clr4: {color4};
  clr5: {color5};
  clr6: {color6};

  accent: {{{{custom.myaccent}}}};
  altaccent: {{{{custom.mytextacc}}}};

sel-bg: @clr4;
  background-color: transparent;

  highlight: underline bold;
  font: "{{{{ custom.monofont }}}} 16";
}}
