set -g @ACCENTCL "#5083C7"
set -g @BGDIM "#1b0c0e"
set -g status-style 'fg=color15 bg=color0'
# setw -g window-status-style 'fg=color7'
# setw -g window-status-current-style 'bg=#261A1D fg=color15 bold'
set -g window-status-bell-style 'bg=red,nobold'
# set -g popup-border-style "fg=color7 bg=default"
set -wg mode-style 'bg=#5083C7'
