$font = Lilex Nerd Font Propo = $clrbg

$clrbg = rgb(8491B0)

general {
    hide_cursor = true
    fail_timeout = 2000
}

background {
    monitor =
	color = $clrbg
}

label {
    monitor =
    text = cmd[update:60000] bash ~/.config/hypr/scripts/lockinfo.sh
    # color = $clr.green
    font_size = 28
    font_family = $font
	text_align = top

	zindex = 0
	position = 0, -350
	halign = center
	valign = top
}

input-field {
    monitor =
    size = 100%, 0
    outline_thickness = 10
    dots_size = 1
    dots_spacing = 0.2
	dots_text_format = *
	placeholder_text = <span size='28pt'><b>$PAMPROMPT</b></span>
    outer_color = $clrbg
    inner_color = $clr.black
    font_color = $clr.fg
    check_color = $clr.blue
    fail_color = $clr.peach
    fade_on_empty = false
	swap_font_color = true
	hide_input = true
	hide_input_base_color = $clr.green
    font_family = $font
	fail_text = <span size='28pt'><i>$PAMFAIL <b>($ATTEMPTS)</b></i></span>
	zindex = 2
	rounding = 0
    position = 0, -18
    halign = center
    valign = top
}
