foreground            #DEDCD3
background            #1D1F21
selection_foreground  #DEDCD3
selection_background  #3a4451

active_tab_foreground     #DEDCD3
active_tab_background     #33373B
inactive_tab_foreground   #454A4F
inactive_tab_background   #1D1F21

active_border_color   #6A779C
inactive_border_color #33373B
url_color             #6B8EAD

# Standard ANSI
color0       #1D1F21
color8       #454A4F
color1       #C46767
color9       #E09696
color2       #86A672
color10      #AFCF9B
color3       #C2A36B
color11      #E3C78B
color4       #6B8EAD
color12      #93B5D1
color5       #A375A3
color13      #C9A2C9
color6       #6BA39C
color14      #94CDC5
color7       #99978F
color15      #DEDCD3
