foreground            #BDBBB0
background            #1F2121
selection_foreground  #BDBBB0
selection_background  #3d4f4f

active_tab_foreground     #BDBBB0
active_tab_background     #353A3A
inactive_tab_foreground   #525757
inactive_tab_background   #1F2121

active_border_color   #8A918A
inactive_border_color #353A3A
url_color             #82A9D1

# Standard ANSI
color0       #292B2B
color8       #525757
color1       #D18282
color9       #E69595
color2       #A1D182
color10      #B5E695
color3       #D1C082
color11      #E6D395
color4       #82A9D1
color12      #95BCE6
color5       #B382D1
color13      #C595E6
color6       #82D1C9
color14      #95E6DD
color7       #BDBBB0
color15      #DEDCD3
