set -g @ACCENTCL "#8A918A"
set -g @BGDIM "#141515"
set -g status-style 'fg=color15 bg=color0'
# setw -g window-status-style 'fg=color7'
# setw -g window-status-current-style 'bg=#1F2121 fg=color15 bold'
set -g window-status-bell-style 'bg=red,nobold'
# set -g popup-border-style "fg=color7 bg=default"
set -wg mode-style 'bg=#8A918A'
