foreground            #E0DEF4
background            #191724
selection_foreground  #E0DEF4
selection_background  #342e5a

active_tab_foreground     #E0DEF4
active_tab_background     #E0DEF4
inactive_tab_foreground   #524F67
inactive_tab_background   #191724

active_border_color   #907AA9
inactive_border_color #E0DEF4
url_color             #286983

# Standard ANSI
color0       #26233A
color8       #524F67
color1       #B4637A
color9       #D6817D
color2       #56949F
color10      #6EB1BC
color3       #EA9D34
color11      #F2B258
color4       #286983
color12      #42819B
color5       #907AA9
color13      #A590BF
color6       #3E8FB0
color14      #54A5C6
color7       #908CAA
color15      #E0DEF4
