foreground            #e9daca
background            #262124
selection_foreground  #e9daca
selection_background  #563e4c

active_tab_foreground     #e9daca
active_tab_background     #5c515a
inactive_tab_foreground   #3d353b
inactive_tab_background   #262124

active_border_color   #b599b1
inactive_border_color #5c515a
url_color             #6592aa

# Standard ANSI
color0       #262124
color8       #3d353b
color1       #d3868c
color9       #e59e89
color2       #8cb3a1
color10      #a1c2b2
color3       #e2b071
color11      #efbe76
color4       #6592aa
color12      #7da8bf
color5       #b599b1
color13      #c9acda
color6       #7bb2b2
color14      #94c7c7
color7       #e9daca
color15      #f5ece3
