foreground            #f7f0e8
background            #0d0b0c
selection_foreground  #f7f0e8
selection_background  #3b2932

active_tab_foreground     #f7f0e8
active_tab_background     #473d43
inactive_tab_foreground   #262124
inactive_tab_background   #0d0b0c

active_border_color   #d4a5ce
inactive_border_color #473d43
url_color             #76b4d4

# Standard ANSI
color0       #0d0b0c
color8       #262124
color1       #ff949c
color9       #ffae94
color2       #a2d4be
color10      #bbf0d7
color3       #ffc87e
color11      #ffd88c
color4       #76b4d4
color12      #92cbed
color5       #d4a5ce
color13      #ecc4ff
color6       #90d6d6
color14      #a8ebeb
color7       #f7f0e8
color15      #ffffff
