ImagePreviewBackend: "chafa"
themes:
  - name: "dark"
    colors:
      - "#EDEDDA"
      - "#242422"
      - "#EDEDDA"
      - "#446063"
      - "#EDEDDA"
      - "#383836"
      - "#242422"
      - "#98c379"
      - "#383836"
      - "#81A1C1"
      - "#302e2c"
      - "#BF616A"
      - "#e06c75"
      - "#A3BE8C"
      - "#B5C985"
      - "#EBCB8B"
      - "#d19a66"
      - "#81A1C1"
      - "#83A4A6"
      - "#B48EAD"
      - "#D18498"
      - "#88C0D0"
      - "#B9C0E5"
      - "#CCCCC0"
      - "#EDEDDA"
  - name: "ink"
    colors:
      - "#141617"
      - "#1D1F21"
      - "#272A2D"
      - "#33373B"
      - "#454A4F"
      - "#616059"
      - "#99978F"
      - "#DEDCD3" 
      - "#6A779C"
      - "#1D1F21"
      - "#C46767" 
      - "#86A672" 
      - "#C2A36B" 
      - "#6B8EAD" 
      - "#A375A3" 
      - "#6BA39C" 
