foreground            #D6D1CB
background            #282624
selection_foreground  #D6D1CB
selection_background  #584c40

active_tab_foreground     #D6D1CB
active_tab_background     #3D3A37
inactive_tab_foreground   #635F59
inactive_tab_background   #282624

active_border_color   #A39E8B
inactive_border_color #3D3A37
url_color             #8594B3

# Standard ANSI
color0       #302E2B
color8       #635F59
color1       #B38585
color9       #C79797
color2       #8B9E8B
color10      #9FB39F
color3       #B39E85
color11      #C7B397
color4       #8594B3
color12      #97A7C7
color5       #9E8BA3
color13      #B39FB3
color6       #85A3A3
color14      #97C7C7
color7       #D6D1CB
color15      #E8E4DF
