set -g @ACCENTCL "#A39E8B"
set -g @BGDIM "#1F1D1C"
set -g status-style 'fg=color15 bg=color0'
# setw -g window-status-style 'fg=color7'
# setw -g window-status-current-style 'bg=#282624 fg=color15 bold'
set -g window-status-bell-style 'bg=red,nobold'
# set -g popup-border-style "fg=color7 bg=default"
set -wg mode-style 'bg=#A39E8B'
