##### Shell & Timing ###########################################################

set -g default-command /bin/zsh
set -s escape-time 0
set-option -g focus-events on

##### Prefix & Core Keys #######################################################

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind r source-file ~/.tmux.conf

##### Terminal & Features ######################################################

set -g default-terminal "screen-256color"
set-option -sa terminal-features 'tmux-256color:RGB'
set-option -g allow-passthrough on

##### Indexing & Session Behavior #############################################

set -g base-index 1
setw -g pane-base-index 1
set -g detach-on-destroy off
set-option -g renumber-windows on
setw -g automatic-rename on

##### Status Line ##############################################################
# set -g status-interval 1
set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'fg=color15 bg=default'
set -g status-left '#S #(git -C #{pane_current_path} rev-parse --is-inside-work-tree &>/dev/null && echo "($(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD)$(git -C #{pane_current_path} describe --tags --abbrev=0 2>/dev/null | sed "s/^/ /"))")'
set -g status-left-style 'fg=color15'
set -g status-left-length 100
set -g status-right-length 100
set -g status-right '#(tmux ls 2>/dev/null | wc -l | tr -d " \n")#(h=$(hostname); [ "$h" = "ajfhome" ] && echo "" || echo " remote $h")'
setw -g window-status-style 'fg=color15'
setw -g window-status-current-style 'bg=color15 fg=color0 bold'
setw -g window-status-format " #I:#{s_.*\\\\|\.exe__:pane_current_command} "
setw -g window-status-current-format ' #I:#{s_.*\\\\|\.exe__:pane_current_command} '
setw -g window-status-separator ""
##### Mouse & Copy Mode ########################################################
set -g mouse on

setw -g mode-keys vi

# Copy-mode helpers
bind a copy-mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi Y send -X copy-pipe-end-of-line 'xclip -in -selection clipboard'
# Bind Prefix + / to enter copy mode and immediately prompt for a forward search string
bind / copy-mode \; send-keys / \; send-keys -X search-forward

##### Pane/Window Navigation ###################################################

bind -r ^ last-window
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

##### Popups ###################################################################

set -g popup-border-style "fg=color7 bg=default"

##### Style-Other ##############################################################

set -wg mode-style bg=blue

##### Custom Launchers #########################################################

bind-key -r e run-shell "tmux neww tm-sess"
bind-key -r g run-shell "openrepoweb.sh"

bind-key -r o run-shell "tmux neww pdf-picker.sh"
bind-key -r D run-shell "tm-sess ~/documents"
bind-key -r 0 run-shell "tm-sess ~ _home"
bind-key -r f run-shell "tmux neww smartfilemaker"
bind-key -r C run-shell "tm-sess ~/dotfiles"
bind-key -r V run-shell "tm-sess ~/.nvim/nvim/.config/nvim"
bind-key -r S run-shell "tm-sess-pwd"
bind-key -r P run-shell -b "tmuxfzflaunch"
bind-key -r q run-shell "tmux display-popup -E -w 80% -h 80% nvim ~/documents/.questions.md"
bind-key -r t run-shell "tmux neww fzf-tests.sh"
bind-key -r . switch-client -l
bind-key -r TAB switch-client -p
