foreground            #D6C9C2
background            #242121
selection_foreground  #D6C9C2
selection_background  #533f3f

active_tab_foreground     #D6C9C2
active_tab_background     #3B3636
inactive_tab_foreground   #5E5656
inactive_tab_background   #242121

active_border_color   #D48D6A
inactive_border_color #3B3636
url_color             #7B92A2

# Standard ANSI
color0       #2E2A2A
color8       #5E5656
color1       #B36D6D
color9       #C48585
color2       #92A67D
color10      #A9B99A
color3       #D4A373
color11      #E1B992
color4       #7B92A2
color12      #92A7B5
color5       #A68A9F
color13      #B8A2B3
color6       #8AA6A2
color14      #A2B8B5
color7       #D6C9C2
color15      #E5DCD6
