cursor {{colors.on_surface.default.hex}}
cursor_text_color {{colors.on_surface_variant.default.hex}}

foreground            {{colors.on_surface.default.hex}}
background            {{colors.surface.default.hex}}
selection_foreground  {{colors.on_secondary.default.hex}}
selection_background  {{colors.secondary_fixed_dim.default.hex}}
url_color             {{colors.primary.default.hex}}

active_tab_foreground     {{colors.surface.default.hex}}
active_tab_background     {{colors.on_surface.default.hex}}
inactive_tab_foreground   {{colors.on_surface.default.hex}}
inactive_tab_background   {{colors.surface.default.hex}}

active_border_color   {{colors.on_surface.default.hex}}
inactive_border_color {{colors.surface.default.hex}}

color0      {{custom.color0}}
color8      {{custom.color8}}
color1      {{custom.color1}}
color9      {{custom.color9}}
color2      {{custom.color2}}
color10     {{custom.color10}}
color3      {{custom.color3}}
color11     {{custom.color11}}
color4      {{custom.color4}}
color12     {{custom.color12}}
color5      {{custom.color5}}
color13     {{custom.color13}}
color6      {{custom.color6}}
color14     {{custom.color14}}
color7      {{custom.color7}}
color15     {{custom.color15}}
