# vim:fileencoding=utf-8:foldmethod=marker
include ~/.config/matugen/cache/kitty-colors.conf

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
modify_font cell_height 100%
font_size 19.0
shell_integration no-cursor
sync_to_monitor no

dynamic_background_opacity yes
map kitty_mod+i           set_background_opacity 1

map kitty_mod+o           set_background_opacity 0.7

hide_window_decorations yes
window_padding_width 0 0
placement_strategy top

cursor none
shell_integration no-cursor
cursor_shape block
cursor_blink_interval -1

tab_bar_edge                      bottom
tab_bar_margin_width 0
tab_bar_align center
tab_title_max_length          27
tab_bar_style separator
tab_separator ""
tab_title_template              " {index}:{title[title.rfind('/')+1:]} "
active_tab_title_template  " {fmt.fg.color0}{index}:{title[title.rfind('/')+1:]} "
active_tab_font_style   bold
