foreground            #8B949E
background            #16181B
selection_foreground  #8B949E
selection_background  #354762

active_tab_foreground     #8B949E
active_tab_background     #2e3137
inactive_tab_foreground   #474D54
inactive_tab_background   #16181B

active_border_color   #4D6A85
inactive_border_color #2e3137
url_color             #5E778C

# Standard ANSI
color0       #1E2125
color8       #474D54
color1       #855459
color9       #996267
color2       #637D68
color10      #749179
color3       #8F7D5D
color11      #A38E6A
color4       #5E778C
color12      #6C88A1
color5       #826A80
color13      #967B94
color6       #608287
color14      #6E959B
color7       #7D868F
color15      #95A0AA
