foreground            #D4D9C7
background            #242826
selection_foreground  #D4D9C7
selection_background  #40584c

active_tab_foreground     #D4D9C7
active_tab_background     #383E3B
inactive_tab_foreground   #5A635F
inactive_tab_background   #242826

active_border_color   #8DA38D
inactive_border_color #383E3B
url_color             #8D9AB8

# Standard ANSI
color0       #2C312F
color8       #5A635F
color1       #B88D8D
color9       #C9A7A7
color2       #97B88D
color10      #AFC9A7
color3       #B8B08D
color11      #C9C3A7
color4       #8D9AB8
color12      #A7B1C9
color5       #B38DB8
color13      #C5A7C9
color6       #8DB8B2
color14      #A7C9C4
color7       #D4D9C7
color15      #E4E8DB
